version: "3.9"

services:
  dev:
    container_name: chocolate-node-dev
    image: paritytech/ci-linux:ba887019-20210411
    working_dir: /var/www/chocolate
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/chocolate/.cargo
    volumes:
      - .:/var/www/chocolate
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/chocolate --dev --ws-external"
