[package]
name = "chocolate-node-constants"
version = "0.1.0"
edition = "2021"
description = "Some constants for the chocolate node with helpful methods"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
